apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtual-accelerator
resources:
  - ../../base
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ghcr.io/slaclab/virtual-accelerator-digital-twin
    newTag: feature-prometheus

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: virtual-accelerator
configMapGenerator:
  - name: va-config
    namespace: virtual-accelerator
    behavior: create
    literals:
      - MODEL=cu_hxr_staged
      - REMOTE_INPUTS=true
      - PV_SUFFIX_ML=_CU_HXR_LUME_ML_DT
      - PV_SUFFIX_PH=_CU_HXR_LUME_PH_DT
      - PV_RENAMES={"sigma_z":"OTRS:IN20:571:ZRMS","norm_emit_x":"OTRS:IN20:571:EMITN_X","norm_emit_y":"OTRS:IN20:571:EMITN_Y"}
      - END_ELEMENT=OTR4
      - N_PARTICLES=1000
      - LOG_LEVEL=DEBUG
      - LCLS_LATTICE=/opt/lcls-lattice
      - KMP_DUPLICATE_LIB_OK=TRUE
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - TORCH_NUM_THREADS=1
      - EPICS_PVA_AUTO_ADDR_LIST=NO
      - EPICS_PVA_BROADCAST_PORT=0
      - EPICS_PVA_NAME_SERVERS=epics-proxy.epics-socat-proxy:5169
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - EPICS_CA_ADDR_LIST=
      - EPICS_CA_NAME_SERVERS=epics-proxy.epics-socat-proxy:5065
      - PYEPICS_LIBCA=/opt/conda/lib/libca.so
      - MALLOC_ARENA_MAX=1
      - MALLOC_MMAP_THRESHOLD_=131072
      - MEM_LOG_INTERVAL_S=60