apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: virtual-accelerator
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
images:
  - name: ghcr.io/slaclab/virtual-accelerator-digital-twin
    newTag: latest
