apiVersion: v1
kind: Service
metadata:
  name: virtual-accelerator
  namespace: virtual-accelerator
spec:
  selector:
    app: virtual-accelerator
  ports:
    - name: pva-tcp
      port: 5075
      targetPort: 5075
      protocol: TCP
    - name: pva-udp
      port: 5076
      targetPort: 5076
      protocol: UDP
